version: '3.4'
services:
  client:
    container_name: client
    build:
      context: ./client
      target: development-build-stage
      dockerfile: Dockerfile
    working_dir: /app
    stdin_open: true
    tty: true
    volumes:
      - ./client/:/app
    ports:
      - 3000:3000
    networks:
      - frontend
  server:
    container_name: server
    build:
      context: ./server
      target: development-build-stage
      dockerfile: Dockerfile
    working_dir: /app
    stdin_open: true
    tty: true
    volumes:
      - ./server:/app
    ports:
      - 9000:9000
    networks:
      - frontend
      - backend
  db:
    image: postgres:13.3-alpine
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: amriksd
      POSTGRES_PASSWORD: supersecurepassword
      POSTGRES_DB: jwt
      PGDATA: /dbdata
    volumes:
      - ./db:/dbdata
    ports:
      - 5432:5432
    networks:
      - backend

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge

volumes:
  data:
    driver: local
