version: '3.4'
services:
  client:
    container_name: client
    build:
      context: ./client
      target: dev
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    networks:
      - frontend
    volumes:
      - ./client:/app
      - node_modules_client:/app/node_modules/

  server:
    container_name: server
    build:
      context: ./server
      target: dev
      dockerfile: Dockerfile
    working_dir: /app
    ports:
      - 9000:9000
    networks:
      - frontend
      - db
    volumes:
      - ./server:/app
      - node_modules_server:/app/node_modules/

  db:
    image: postgres:13.3-alpine
    container_name: jiraDB
    environment:
      POSTGRES_USER: amriksd
      POSTGRES_PASSWORD: supersecurepassword
      POSTGRES_DB: jwt
    ports:
      - 5432:5432
    networks:
      - db

networks:
  frontend:
    driver: bridge
  db:
    driver: bridge

volumes:
  node_modules_server: {}
  node_modules_client: {}
