version: "3.4"
services:
  client:
    container_name: client
    build:
      context: ./client
      target: dev
      dockerfile: Dockerfile
    image: amriksd/jira-client
    working_dir: /app
    stdin_open: true
    tty: true
    ports:
      - 3000:3000
    networks:
      - frontend
  server:
    container_name: server
    build:
      context: ./server
      target: dev
      dockerfile: Dockerfile
    image: amriksd/jira-server
    working_dir: /app
    stdin_open: true
    tty: true
    ports:
      - 9000:9000
    networks:
      - frontend
      - backend
  db:
    image: postgres:13.3-alpine
    container_name: jiraDB
    environment:
      POSTGRES_USER: amriksd
      POSTGRES_PASSWORD: supersecurepassword
      POSTGRES_DB: jwt
    ports:
      - 5432:5432
    networks:
      - backend

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
