version: "3.4"
services:
  client:
    container_name: client
    build:
      context: ./client
      target: development-build-stage
      dockerfile: Dockerfile
    working_dir: /app
    stdin_open: true
    tty: true
    volumes:
      - ./client/:/app
    ports:
      - 3000:3000
    networks:
      - backend
  server:
    container_name: server
    build:
      context: ./server
      target: development-build-stage
      dockerfile: Dockerfile
    working_dir: /app
    stdin_open: true
    tty: true
    volumes:
      - ./server:/app
      - /app/node_modules
    ports:
      - 9000:9000
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  data:
    driver: local
