name: Docker Builds

on:
  push:
    branches: [ main ]
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
 
  build:
    runs-on: ubuntu-latest # has docker installed already
    steps:
      - uses: actions/checkout@v2
      - name: login to docker
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      - name: build docker images
        run: docker-compose build
      - name: push docker images
        run: docker-compose push
