name: Docker Builds

on:
  push:
    branches: [ main ]
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
 
  build:
    runs-on: ubuntu-latest # has docker installed already
    steps:
      - uses: actions/checkout@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: build & push client image
        run: |
          docker build --target prod client -t amriksd/jira-client
          docker push amriksd/jira-client
      - name: build & push server docker image
        run: | 
          docker build --target prod server -t amriksd/jira-server
          docker push amriksd/jira-server

